In [10]:

import pandas as pd
import numpy as np

# read the csv dataset for diamonds

df = pd.read_csv("diamonds.csv")
df.head()

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z
0,1,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
1,2,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,3,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
3,4,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63
4,5,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75

In [11]:
#Number of records in dataset
df.tail()

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z
53935,53936,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50
53936,53937,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61
53937,53938,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56
53938,53939,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74
53939,53940,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64

In [12]:
#Clean the data:
#Create list of true/false values
dupe = df.duplicated() 
#Shwo rows where duplicate is true
df[dupe]

Empty DataFrame
Columns: [Unnamed: 0, carat, cut, color, clarity, depth, table, price, x, y, z]
Index: []

In [13]:
#show data types in the dataset
df.dtypes

Unnamed: 0      int64
carat         float64
cut            object
color          object
clarity        object
depth         float64
table         float64
price           int64
x             float64
y             float64
z             float64
dtype: object

In [18]:
#Count rows including NA values
len(df)

53940

In [16]:
#number of non-NA values
df.count()

Unnamed: 0    53940
carat         53940
cut           53940
color         53940
clarity       53940
depth         53940
table         53940
price         53940
x             53940
y             53940
z             53940
dtype: int64

In [14]:
#drop rows with any missing data
df_no_missing = df.dropna()
df_no_missing

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z
0,1,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
1,2,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,3,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
3,4,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63
4,5,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75
5,6,0.24,Very Good,J,VVS2,62.8,57.0,336,3.94,3.96,2.48
6,7,0.24,Very Good,I,VVS1,62.3,57.0,336,3.95,3.98,2.47
7,8,0.26,Very Good,H,SI1,61.9,55.0,337,4.07,4.11,2.53
8,9,0.22,Fair,E,VS2,65.1,61.0,337,3.87,3.78,2.49
9,10,0.23,Very Good,H,VS1,59.4,61.0,338,4.00,4.05,2.39
10,11,0.30,Good,J,SI1,64.0,55.0,339,4.25,4.28,2.73
11,12,0.23,Ideal,J,VS1,62.8,56.0,340,3.93,3.90,2.46
12,13,0.22,Premium,F,SI1,60.4,61.0,342,3.88,3.84,2.33
13,14,0.31,Ideal,J,SI2,62.2,54.0,344,4.35,4.37,2.71
14,15,0.20,Premium,E,SI2,60.2,62.0,345,3.79,3.75,2.27
15,16,0.32,Premium,E,I1,60.9,58.0,345,4.38,4.42,2.68
16,17,0.30,Ideal,I,SI2,62.0,54.0,348,4.31,4.34,2.68
17,18,0.30,Good,J,SI1,63.4,54.0,351,4.23,4.29,2.70
18,19,0.30,Good,J,SI1,63.8,56.0,351,4.23,4.26,2.71
19,20,0.30,Very Good,J,SI1,62.7,59.0,351,4.21,4.27,2.66
20,21,0.30,Good,I,SI2,63.3,56.0,351,4.26,4.30,2.71
21,22,0.23,Very Good,E,VS2,63.8,55.0,352,3.85,3.92,2.48
22,23,0.23,Very Good,H,VS1,61.0,57.0,353,3.94,3.96,2.41
23,24,0.31,Very Good,J,SI1,59.4,62.0,353,4.39,4.43,2.62
24,25,0.31,Very Good,J,SI1,58.1,62.0,353,4.44,4.47,2.59
25,26,0.23,Very Good,G,VVS2,60.4,58.0,354,3.97,4.01,2.41
26,27,0.24,Premium,I,VS1,62.5,57.0,355,3.97,3.94,2.47
27,28,0.30,Very Good,J,VS2,62.2,57.0,357,4.28,4.30,2.67
28,29,0.23,Very Good,D,VS2,60.5,61.0,357,3.96,3.97,2.40
29,30,0.23,Very Good,F,VS1,60.9,57.0,357,3.96,3.99,2.42
...,...,...,...,...,...,...,...,...,...,...,...
53910,53911,0.70,Premium,E,SI1,60.5,58.0,2753,5.74,5.77,3.48
53911,53912,0.57,Premium,E,IF,59.8,60.0,2753,5.43,5.38,3.23
53912,53913,0.61,Premium,F,VVS1,61.8,59.0,2753,5.48,5.40,3.36
53913,53914,0.80,Good,G,VS2,64.2,58.0,2753,5.84,5.81,3.74
53914,53915,0.84,Good,I,VS1,63.7,59.0,2753,5.94,5.90,3.77
53915,53916,0.77,Ideal,E,SI2,62.1,56.0,2753,5.84,5.86,3.63
53916,53917,0.74,Good,D,SI1,63.1,59.0,2753,5.71,5.74,3.61
53917,53918,0.90,Very Good,J,SI1,63.2,60.0,2753,6.12,6.09,3.86
53918,53919,0.76,Premium,I,VS1,59.3,62.0,2753,5.93,5.85,3.49
53919,53920,0.76,Ideal,I,VVS1,62.2,55.0,2753,5.89,5.87,3.66
53920,53921,0.70,Very Good,E,VS2,62.4,60.0,2755,5.57,5.61,3.49
53921,53922,0.70,Very Good,E,VS2,62.8,60.0,2755,5.59,5.65,3.53
53922,53923,0.70,Very Good,D,VS1,63.1,59.0,2755,5.67,5.58,3.55
53923,53924,0.73,Ideal,I,VS2,61.3,56.0,2756,5.80,5.84,3.57
53924,53925,0.73,Ideal,I,VS2,61.6,55.0,2756,5.82,5.84,3.59
53925,53926,0.79,Ideal,I,SI1,61.6,56.0,2756,5.95,5.97,3.67
53926,53927,0.71,Ideal,E,SI1,61.9,56.0,2756,5.71,5.73,3.54
53927,53928,0.79,Good,F,SI1,58.1,59.0,2756,6.06,6.13,3.54
53928,53929,0.79,Premium,E,SI2,61.4,58.0,2756,6.03,5.96,3.68
53929,53930,0.71,Ideal,G,VS1,61.4,56.0,2756,5.76,5.73,3.53
53930,53931,0.71,Premium,E,SI1,60.5,55.0,2756,5.79,5.74,3.49
53931,53932,0.71,Premium,F,SI1,59.8,62.0,2756,5.74,5.73,3.43
53932,53933,0.70,Very Good,E,VS2,60.5,59.0,2757,5.71,5.76,3.47
53933,53934,0.70,Very Good,E,VS2,61.2,59.0,2757,5.69,5.72,3.49
53934,53935,0.72,Premium,D,SI1,62.7,59.0,2757,5.69,5.73,3.58
53935,53936,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50
53936,53937,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61
53937,53938,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56
53938,53939,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74
53939,53940,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64

In [15]:
#Run descriptive statistics 
df.describe()

,Unnamed: 0,carat,depth,table,price,x,y,z
count,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000
mean,26970.500000,0.797940,61.749405,57.457184,3932.799722,5.731157,5.734526,3.538734
std,15571.281097,0.474011,1.432621,2.234491,3989.439738,1.121761,1.142135,0.705699
min,1.000000,0.200000,43.000000,43.000000,326.000000,0.000000,0.000000,0.000000
25%,13485.750000,0.400000,61.000000,56.000000,950.000000,4.710000,4.720000,2.910000
50%,26970.500000,0.700000,61.800000,57.000000,2401.000000,5.700000,5.710000,3.530000
75%,40455.250000,1.040000,62.500000,59.000000,5324.250000,6.540000,6.540000,4.040000
max,53940.000000,5.010000,79.000000,95.000000,18823.000000,10.740000,58.900000,31.800000

In [19]:
import statsmodels.formula.api as smf

In [24]:
#Run a correlation on the dataset.
df.corr()

,Unnamed: 0,carat,depth,table,price,x,y,z
Unnamed: 0,1.000000,-0.377983,-0.034800,-0.100830,-0.306873,-0.405440,-0.395843,-0.399208
carat,-0.377983,1.000000,0.028224,0.181618,0.921591,0.975094,0.951722,0.953387
depth,-0.034800,0.028224,1.000000,-0.295779,-0.010647,-0.025289,-0.029341,0.094924
table,-0.100830,0.181618,-0.295779,1.000000,0.127134,0.195344,0.183760,0.150929
price,-0.306873,0.921591,-0.010647,0.127134,1.000000,0.884435,0.865421,0.861249
x,-0.405440,0.975094,-0.025289,0.195344,0.884435,1.000000,0.974701,0.970772
y,-0.395843,0.951722,-0.029341,0.183760,0.865421,0.974701,1.000000,0.952006
z,-0.399208,0.953387,0.094924,0.150929,0.861249,0.970772,0.952006,1.000000

In [32]:
#1. Run a regression.   How does price relate to carat, x, y and z? 
result = smf.ols('price ~ carat + x + y + z', data=df).fit()

In [33]:
result.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  price   R-squared:                       0.854
Model:                            OLS   Adj. R-squared:                  0.854
Method:                 Least Squares   F-statistic:                 7.892e+04
Date:                Mon, 04 Mar 2019   Prob (F-statistic):               0.00
Time:                        17:32:02   Log-Likelihood:            -4.7187e+05
No. Observations:               53940   AIC:                         9.437e+05
Df Residuals:                   53935   BIC:                         9.438e+05
Df Model:                           4
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept   1921.1740    104.373     18.407      0.000    1716.601    2125.747
carat       1.023e+04     62.937    162.607      0.000    1.01e+04    1.04e+04
x           -884.2091     40.470    -21.848      0.000    -963.532    -804.887
y            166.0384     25.858      6.421      0.000     115.356     216.721
z           -576.2035     39.282    -14.668      0.000    -653.197    -499.210
==============================================================================
Omnibus:                    14400.324   Durbin-Watson:                   1.198
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           336485.128
Skew:                           0.743   Prob(JB):                         0.00
Kurtosis:                      15.145   Cond. No.                         171.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

******Result:  Price is related to carat, depth and table ???  Don't know how to interpret

In [37]:
#Remove y from correlation - not strong relationship
result = smf.ols('price ~ x + z', data=df).fit()
result.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  price   R-squared:                       0.782
Model:                            OLS   Adj. R-squared:                  0.782
Method:                 Least Squares   F-statistic:                 9.694e+04
Date:                Mon, 04 Mar 2019   Prob (F-statistic):               0.00
Time:                        17:44:58   Log-Likelihood:            -4.8265e+05
No. Observations:               53940   AIC:                         9.653e+05
Df Residuals:                   53937   BIC:                         9.653e+05
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept   -1.41e+04     41.761   -337.735      0.000   -1.42e+04    -1.4e+04
x           2985.6986     29.767    100.304      0.000    2927.356    3044.041
z            261.5216     47.316      5.527      0.000     168.781     354.262
==============================================================================
Omnibus:                    18951.077   Durbin-Watson:                   0.438
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           145498.097
Skew:                           1.486   Prob(JB):                         0.00
Kurtosis:                      10.477   Cond. No.                         48.1
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

******Result:  Don't know how to interpret????

In [38]:
#set coefficient to 0
result = smf.ols(formula='price ~ x + y + z - 1', data=df).fit()
result.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  price   R-squared:                       0.656
Model:                            OLS   Adj. R-squared:                  0.656
Method:                 Least Squares   F-statistic:                 3.432e+04
Date:                Mon, 04 Mar 2019   Prob (F-statistic):               0.00
Time:                        17:47:06   Log-Likelihood:            -5.1329e+05
No. Observations:               53940   AIC:                         1.027e+06
Df Residuals:                   53937   BIC:                         1.027e+06
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x           1145.0222     71.850     15.936      0.000    1004.196    1285.849
y           -108.5958     55.702     -1.950      0.051    -217.773       0.582
z           -420.3561     83.928     -5.009      0.000    -584.855    -255.857
==============================================================================
Omnibus:                    19355.327   Durbin-Watson:                   0.021
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            57590.238
Skew:                           1.925   Prob(JB):                         0.00
Kurtosis:                       6.288   Cond. No.                         64.8
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

Result?????: don't know how to interpret

In [34]:
#2.  How does price relate to carat, depth and table? 
result = smf.ols('price ~ carat + depth + table', data=df).fit()

In [35]:
result.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  price   R-squared:                       0.854
Model:                            OLS   Adj. R-squared:                  0.854
Method:                 Least Squares   F-statistic:                 1.049e+05
Date:                Mon, 04 Mar 2019   Prob (F-statistic):               0.00
Time:                        17:36:11   Log-Likelihood:            -4.7194e+05
No. Observations:               53940   AIC:                         9.439e+05
Df Residuals:                   53936   BIC:                         9.439e+05
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     1.3e+04    390.918     33.264      0.000    1.22e+04    1.38e+04
carat       7858.7705     14.151    555.356      0.000    7831.035    7886.506
depth       -151.2363      4.820    -31.378      0.000    -160.683    -141.789
table       -104.4728      3.141    -33.259      0.000    -110.630     -98.316
==============================================================================
Omnibus:                    14107.737   Durbin-Watson:                   1.015
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           154392.067
Skew:                           0.945   Prob(JB):                         0.00
Kurtosis:                      11.070   Cond. No.                     5.02e+03
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.02e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

>Result????:  Don't know how to interpret

In [39]:
#remove carat from regression
result = smf.ols('price ~ depth + table', data=df).fit()
result.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  price   R-squared:                       0.017
Model:                            OLS   Adj. R-squared:                  0.017
Method:                 Least Squares   F-statistic:                     465.3
Date:                Mon, 04 Mar 2019   Prob (F-statistic):          4.62e-201
Time:                        17:51:54   Log-Likelihood:            -5.2331e+05
No. Observations:               53940   AIC:                         1.047e+06
Df Residuals:                   53937   BIC:                         1.047e+06
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept  -1.508e+04   1004.719    -15.014      0.000   -1.71e+04   -1.31e+04
depth         82.2616     12.445      6.610      0.000      57.869     106.654
table        242.5835      7.979     30.402      0.000     226.944     258.223
==============================================================================
Omnibus:                    15207.938   Durbin-Watson:                   0.041
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            34864.819
Skew:                           1.622   Prob(JB):                         0.00
Kurtosis:                       5.234   Cond. No.                     4.98e+03
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 4.98e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

Results:  ???????  Don't know how to interpret

In [40]:
#set coefficient to 0
result = smf.ols(formula='price ~ carat + depth + table - 1', data=df).fit()
result.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  price   R-squared:                       0.924
Model:                            OLS   Adj. R-squared:                  0.924
Method:                 Least Squares   F-statistic:                 2.194e+05
Date:                Mon, 04 Mar 2019   Prob (F-statistic):               0.00
Time:                        17:52:56   Log-Likelihood:            -4.7249e+05
No. Observations:               53940   AIC:                         9.450e+05
Df Residuals:                   53937   BIC:                         9.450e+05
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
carat       7797.8694     14.175    550.114      0.000    7770.086    7825.653
depth         -6.9151      2.121     -3.261      0.001     -11.072      -2.758
table        -32.4782      2.300    -14.122      0.000     -36.986     -27.970
==============================================================================
Omnibus:                    13942.521   Durbin-Watson:                   0.994
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           157317.193
Skew:                           0.922   Prob(JB):                         0.00
Kurtosis:                      11.161   Cond. No.                         180.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

REsults????:  Don't know how to interpret

In [44]:
Location = "datasets/tamiami.csv"

df = pd.read_csv(Location)
df.head()

,Cart Location,Hot Dog Sales,Employees in Nearby Office Buildings,Num of Nearby Restaurants,Num of Other Food Carts Nearby,Price
0,1,100,1600,8,12,4.16
1,2,80,1200,6,13,4.63
2,3,450,2800,19,6,0.50
3,4,580,4300,19,2,0.47
4,5,100,1400,6,13,4.24

In [45]:
columns = ['location', 'sales', 'employees', 'restaurants', 'foodcarts', 'price']

#change column names for readability
df.columns = columns
df.head()

   location  sales  employees  restaurants  foodcarts  price
0         1    100       1600            8         12   4.16
1         2     80       1200            6         13   4.63
2         3    450       2800           19          6   0.50
3         4    580       4300           19          2   0.47
4         5    100       1400            6         13   4.24

In [46]:
#Number of records in dataset
df.tail()

    location  sales  employees  restaurants  foodcarts  price
25        26     60        900            5         12   4.64
26        27    200       1700           11         12   2.72
27        28    280       1900           10          8   1.79
28        29    500       3000           15          4   0.48
29        30    460       2900           17          5   0.53

In [47]:
#show data types in the dataset
df.dtypes

location         int64
sales            int64
employees        int64
restaurants      int64
foodcarts        int64
price          float64
dtype: object

In [48]:
#Clean the data:
#Create list of true/false values
dupe = df.duplicated() 
#Shwo rows where duplicate is true
df[dupe]

Empty DataFrame
Columns: [location, sales, employees, restaurants, foodcarts, price]
Index: []

In [50]:
#drop rows with any missing data
df_no_missing = df.dropna()
df_no_missing

    location  sales  employees  restaurants  foodcarts  price
0          1    100       1600            8         12   4.16
1          2     80       1200            6         13   4.63
2          3    450       2800           19          6   0.50
3          4    580       4300           19          2   0.47
4          5    100       1400            6         13   4.24
5          6     50        700            4         11   4.21
6          7    120       1600            9         13   3.53
7          8    560       3500           18          2   0.45
8          9    250       1900           15          9   2.10
9         10    290       2400           13          9   1.59
10        11    520       3100           16          3   0.47
11        12    480       2700           18          4   0.53
12        13    510       3200           17          3   0.55
13        14     90       1600            8         16   4.54
14        15    110       1500            7         13   3.60
15        16    210       1600           10         11   2.81
16        17     40        600            2         14   4.99
17        18    180       1800            7         14   2.82
18        19     90       1500            9         14   4.21
19        20     80       1500            7         14   4.29
20        21    190       1900            8         13   3.13
21        22    240       1500           16         16   2.34
22        23    300       2500           15          9   1.61
23        24    260       1500           14         13   1.84
24        25    420       2600           18          6   0.51
25        26     60        900            5         12   4.64
26        27    200       1700           11         12   2.72
27        28    280       1900           10          8   1.79
28        29    500       3000           15          4   0.48
29        30    460       2900           17          5   0.53

In [49]:
#Run a correlation on the dataset.
df.corr()

             location     sales  employees  restaurants  foodcarts     price
location     1.000000  0.042705  -0.068923     0.049701   0.077219 -0.138444
sales        0.042705  1.000000   0.943238     0.913674  -0.919762 -0.966378
employees   -0.068923  0.943238   1.000000     0.856976  -0.874692 -0.881540
restaurants  0.049701  0.913674   0.856976     1.000000  -0.761793 -0.933951
foodcarts    0.077219 -0.919762  -0.874692    -0.761793   1.000000  0.860154
price       -0.138444 -0.966378  -0.881540    -0.933951   0.860154  1.000000

In [52]:
import statsmodels.formula.api as smf

In [53]:
#Regression
result = smf.ols('sales ~ location + employees + price', data=df).fit()

In [54]:
result.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  sales   R-squared:                       0.972
Model:                            OLS   Adj. R-squared:                  0.968
Method:                 Least Squares   F-statistic:                     295.6
Date:                Mon, 04 Mar 2019   Prob (F-statistic):           3.35e-20
Time:                        18:29:05   Log-Likelihood:                -143.82
No. Observations:                  30   AIC:                             295.6
Df Residuals:                      26   BIC:                             301.2
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept    268.1488     57.310      4.679      0.000     150.346     385.951
location      -0.3140      0.732     -0.429      0.672      -1.820       1.191
employees      0.0805      0.016      5.160      0.000       0.048       0.113
price        -67.3533      8.416     -8.003      0.000     -84.653     -50.054
==============================================================================
Omnibus:                        0.015   Durbin-Watson:                   2.482
Prob(Omnibus):                  0.993   Jarque-Bera (JB):                0.192
Skew:                           0.031   Prob(JB):                        0.909
Kurtosis:                       2.613   Cond. No.                     2.22e+04
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.22e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [55]:
#remove price from regression
result = smf.ols('sales ~ location + employees', data=df).fit()
result.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  sales   R-squared:                       0.901
Model:                            OLS   Adj. R-squared:                  0.894
Method:                 Least Squares   F-statistic:                     123.4
Date:                Mon, 04 Mar 2019   Prob (F-statistic):           2.63e-14
Time:                        18:30:53   Log-Likelihood:                -162.45
No. Observations:                  30   AIC:                             330.9
Df Residuals:                      27   BIC:                             335.1
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept   -165.7118     33.938     -4.883      0.000    -235.347     -96.077
location       2.1651      1.212      1.786      0.085      -0.322       4.652
employees      0.1932      0.012     15.691      0.000       0.168       0.218
==============================================================================
Omnibus:                        3.780   Durbin-Watson:                   1.973
Prob(Omnibus):                  0.151   Jarque-Bera (JB):                1.548
Skew:                          -0.062   Prob(JB):                        0.461
Kurtosis:                       1.894   Cond. No.                     7.14e+03
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 7.14e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [56]:
#set coefficient to 0
result = smf.ols(formula='sales ~ location + employees + price - 1', data=df).fit()
result.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  sales   R-squared:                       0.984
Model:                            OLS   Adj. R-squared:                  0.982
Method:                 Least Squares   F-statistic:                     549.3
Date:                Mon, 04 Mar 2019   Prob (F-statistic):           2.66e-24
Time:                        18:32:23   Log-Likelihood:                -152.98
No. Observations:                  30   AIC:                             312.0
Df Residuals:                      27   BIC:                             316.2
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
location       1.6656      0.796      2.092      0.046       0.032       3.299
employees      0.1508      0.006     26.444      0.000       0.139       0.162
price        -30.1026      3.635     -8.282      0.000     -37.560     -22.645
==============================================================================
Omnibus:                        4.598   Durbin-Watson:                   2.232
Prob(Omnibus):                  0.100   Jarque-Bera (JB):                1.682
Skew:                           0.029   Prob(JB):                        0.431
Kurtosis:                       1.842   Cond. No.                     1.05e+03
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.05e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

Takeaways:  The most important variable in sales volume is location.